# Generated by Django 3.1.7 on 2021-03-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210303_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='biography',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
